# Generated by Django 5.2.1 on 2025-06-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpscalingTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GraphicsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(choices=[('NVIDIA', 'NVIDIA'), ('AMD', 'AMD'), ('Intel', 'Intel')], max_length=10)),
                ('memory_gb', models.PositiveIntegerField()),
                ('memory_type', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('benchmark_index', models.PositiveIntegerField()),
                ('supported_technologies', models.ManyToManyField(blank=True, related_name='supported_cards', to='cards.upscalingtechnology')),
            ],
        ),
    ]
